language: python
python:
    - 3.9
    - 3.8
    - 3.7
    - 3.6
    - 2.7
    - pypy3
    - pypy2
install:
    - pip install -U tox-travis
    - pip install -U codecov
script: tox
after_success:
    - codecov
notifications:
  email:
    on_success: never
    on_failure: always
